import pandas as pd
import os

#Testing

configfile: "config/config.yaml"

os.environ["PYTHONPATH"] = config["daedalus_src"] + ":" + os.environ.get("PYTHONPATH", "")

REF_FASTAS = [v["full"] for v in config["references"].values()]

allowed_refs = ["ISO1", "Shukla_ISO1", "Yunnan"]
for_contiguity_plot = [v["full"] for k, v in config["references"].items() if k in allowed_refs]

samples = pd.read_csv(config["control_file"], sep="\t")

STRAINS = samples["strain"].tolist()

# Add outgroups
OUTGROUPS = ["w501"]

# Combine them for the phylogeny workflow only
PHYLOGENY_STRAINS = STRAINS + ["ISO1"] + OUTGROUPS

OUTGROUP_READS = {"w501": "data/sra/SRR32930726/SRR32930726.fastq"}

def get_assembly(wc):
    return samples.loc[samples.strain == wc.strain, "assembly"].values[0]

def get_reads(wildcards):
    if wildcards.strain == "ISO1":
        return "data/ISO1_reads/SRR29479668.fastq"
    elif wildcards.strain in OUTGROUP_READS:
        return OUTGROUP_READS[wildcards.strain]
    return samples.loc[samples.strain == wildcards.strain, "reads"].values[0]

def run_module(module, cmd):
    return f"""
    PYTHONPATH={config[module + '_src']}:$PYTHONPATH \
    python -m {module}.cli {cmd}
    """

include: "rules/assembly.smk"
include: "rules/mapping.smk"
include: "rules/quality_control.smk"
include: "rules/aggregate.smk"
include: "rules/phylogeny.smk"
include: "rules/pangenome.smk"
include: "rules/genome_to_genome.smk"
include: "rules/repeatmasker.smk"

rule all:
    input:
        #expand("results/{strain}/mummer/{strain}_r6_main.delta", strain=STRAINS),
        #expand("results/{strain}/curated_assembly/{strain}.curated.fasta", strain=STRAINS),
        #expand("results/{strain}/dotplots/for_curation", strain=STRAINS),
        #expand("results/{strain}/variants", strain=STRAINS),
        #expand("results/{strain}/qc/{strain}_qc.tsv", strain=STRAINS),
        #expand("results/{strain}/compleasm", strain=STRAINS),
        #expand("results/{strain}/busco", strain=STRAINS),
        #expand("results/{strain}/mummer/{strain}_r6_main_curated.delta", strain=STRAINS),
        #expand("results/{strain}/scaffold/{strain}.scaffolded.fasta", strain=STRAINS),
        #expand("results/aggregate/plots/contiguity.png"),
        #expand("results/aggregate/tables/assembly_metrics.tsv"),
        #expand("results/{strain}/qc/{strain}.seqkit.stats.tsv", strain=STRAINS),
        #expand("results/{strain}/qc/{strain}.scaffold.stats.tsv", strain=STRAINS),
        #expand("results/{strain}/phylogeny/mapping/{strain}_ref.bam", strain=PHYLOGENY_STRAINS),
        #"results/aggregate/phylogeny/core_genome.filtered.varsites.fasta.treefile",
        #"results/pangenome/cactus_out/PANGENOME_REF.gfa.gz",
        #expand("results/{strain}/mapping/ISO1_to_{strain}.bam", strain=STRAINS),
        #expand("results/{strain}/mappable_variants/ISO1_to_{strain}.paftools_micro.vcf", strain=STRAINS),
        #expand("results/{strain}/dotplots/curated",strain=STRAINS),
        #expand("results/{strain}/dotplots/curated_all",strain=STRAINS),
        #expand("results/{strain}/dotplots/scaffolded",strain=STRAINS),
        #expand("results/{strain}/qc/{strain}.contig_flow.png",strain=STRAINS),
        #expand("results/{strain}/qc/{strain}.contig_flow.tsv", strain=STRAINS),
        #expand("results/{strain}/variants/{strain}.svmu2.vcf", strain=STRAINS),
        #expand("results/{strain}/variants/svmu2_synteny_plots",strain=STRAINS),
        #expand("results/{strain}/variants/{strain}.chromosome_summary.tsv",strain=STRAINS),
        #expand("results/{strain}/variants/{strain}.sample_summary.tsv",strain=STRAINS),
        #"results/aggregate/phylogeny/core_genome.filtered.varsites.fasta.treefile",
        expand("results/{strain}/repeats/plots/X.panel.pdf",strain=STRAINS),
        expand("results/{strain}/euchromatin/{strain}.euchromatin.bed",strain=STRAINS),