executor: slurm
jobs: 25
latency-wait: 120

default-resources:
  slurm_account: !!str "132714819723"
  slurm_partition: "medium"
  mem_mb: 16000
  runtime: 60

# Note: The 'slurm:' block is often ignored by the new plugin 
# if not nested under 'default-resources' or 'retries'
